#!/bin/bash

GUNICORN_WORKERS=${GUNICORN_WORKERS:-4} # Número de CPU x 2 + 1
GUNICORN_WORKER_TIMEOUT=${GUNICORN_WORKER_TIMEOUT:-120}
GUNICORN_MAX_REQUESTS=${GUNICORN_MAX_REQUESTS:-1000}
GUNICORN_MAX_REQUESTS_JITTER=${GUNICORN_MAX_REQUESTS_JITTER:-100}
GUNICORN_KEEP_ALIVE=${GUNICORN_KEEP_ALIVE:-10}
GUNICORN_GRACEFUL_TIMEOUT=${GUNICORN_GRACEFUL_TIMEOUT:-30}

gunicorn --worker-class uvicorn.workers.UvicornWorker \
  -w "$GUNICORN_WORKERS" \
  -t "$GUNICORN_WORKER_TIMEOUT" \
  --keep-alive="$GUNICORN_KEEP_ALIVE" \
  --max-requests="$GUNICORN_MAX_REQUESTS" \
  --max-requests-jitter="$GUNICORN_MAX_REQUESTS_JITTER" \
  --graceful-timeout="$GUNICORN_GRACEFUL_TIMEOUT" \
  --access-logfile - --error-logfile - \
  -b 0.0.0.0:8000 \
  app.start:app